### ISSUE TITLE
这件事情我第一感觉就是难，但是你做成了，令人佩服

### ISSUE THREAD

**Issue by Nuclear6** [ruiduobao/gaode_MAP_CUN#1]
但是我还是有一些疑问请教下：去哪里收集数据？怎么保证数据更新速度？为什么能坚持做这件事情？

**Comment by xinmans** [comment]
网上爬的？而且要坚持兴趣驱动？牛逼的

**Comment by careteenL** [comment]
同问数据怎么收集的？

**Comment by stellarhalo** [comment]
@ruiduobao 大佬，您的项目非常优秀，我由衷敬佩！已为项目点亮 Star，以表达我的支持与赞赏
